#!/bin/sh

function usage {
    cat <<EOF
    $(basename ${0}) is a tool for phpunit or phpstan (or all) watching executor
Usage:
    $(basename ${0}) phpunit|phpstan|all
Options:
    --help, -h        print this
EOF
}

phpstanLevel=1

case ${1} in

    phpunit)
        executor "vendor/bin/phpunit" --watch='**/*.php' --ignore='node_modules/' --ignore='vendor/'
    ;;

    phpstan)
        executor "vendor/bin/phpstan analyze -c phpstan.neon -l ${phpstanLevel} --no-progress app routes" --watch='**/*.php' --ignore='node_modules/' --ignore='vendor/'
    ;;

    eslint)
        executor "eslint resources/assets/js/*/** --color --quiet --fix --ignore-pattern .eslintignore" --watch='resources/assets/js/**' --ignore='node_modules/' --ignore='vendor/' 
    ;;

    js)
        executor "eslint resources/assets/js/*/** --color --quiet --fix --ignore-pattern .eslintignore" --watch='resources/assets/js/**' --ignore='node_modules/' --ignore='vendor/' 
    ;;


    php)
        executor "vendor/bin/phpunit && vendor/bin/phpstan analyze -c phpstan.neon -l ${phpstanLevel} --no-progress app routes" --watch='**/*.php' --ignore='node_modules/' --ignore='vendor/'
    ;;

    help|--help|-h)
        usage
    ;;

    *)
        executor "vendor/bin/phpunit && vendor/bin/phpstan analyze -c phpstan.neon -l ${phpstanLevel} --no-progress app routes" --watch='**/*.php' --ignore='node_modules/' --ignore='vendor/'
    ;;
esac
