#!/bin/sh

phpstanLevel=1

case ${1} in

    phpunit)
        ./node_modules/@lassehaslev/executor/dist/app.js "vendor/bin/phpunit" --watch='**/*.php' --ignore='node_modules/' --ignore='vendor/'
    ;;

    phpstan)
         ./node_modules/@lassehaslev/executor/dist/app.js "vendor/bin/phpstan analyze -c phpstan.neon -l ${phpstanLevel} --no-progress app routes" --watch='**/*.php' --ignore='node_modules/' --ignore='vendor/'
    ;;

    eslint)
        ./node_modules/@lassehaslev/executor/dist/app.js "eslint resources/assets/js/**/**/**/**/**/** --color --quiet --fix --ignore-pattern .eslintignore" --watch='resources/assets/js/**' --ignore='node_modules/' --ignore='vendor/'
    ;;

    js)
        ./node_modules/@lassehaslev/executor/dist/app.js "eslint resources/assets/js/**/**/**/**/**/** --color --quiet --fix --ignore-pattern .eslintignore" --watch='resources/assets/js/**' --ignore='node_modules/' --ignore='vendor/'
    ;;


    php)
        ./node_modules/@lassehaslev/executor/dist/app.js "vendor/bin/phpunit && vendor/bin/phpstan analyze -c phpstan.neon -l ${phpstanLevel} --no-progress app routes" --watch='**/*.php' --ignore='node_modules/' --ignore='vendor/'
    ;;

    e2e)
        npm run dev &&  ./node_modules/@lassehaslev/executor/dist/app.js "php artisan dusk" --watch='**/*.php' --ignore='node_modules/' --ignore='vendor/'
    ;;

    help|--help|-h)
        usage
    ;;

    *)
        executor "vendor/bin/phpunit && vendor/bin/phpstan analyze -c phpstan.neon -l ${phpstanLevel} --no-progress app routes" --watch='**/*.php' --ignore='node_modules/' --ignore='vendor/'
    ;;
esac
