# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.2-apache-node-browsers
        # environment:
        # - DB_HOST=127.0.0.1
        # - DB_PORT=3306
        # - DB_DATABASE=circle_test
        # - DB_USERNAME=root
        # - DB_PASSWORD=
        # - APP_DEBUG= true
        # - APP_ENV= testing
        # - PROJECT_NAME= 'TESTPROJECT'
      # - image: circleci/mysql:5.7
      #   environment:
      #   - DB_CONNECTION: circle_test
      #   - MYSQL_ALLOW_EMPTY_PASSWORD: true

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/myapp

    steps:
      - checkout

      # - run: sudo docker-php-ext-install pdo_mysql

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "src/composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd src && composer install -n --prefer-dist

      - save_cache:
          build_dir: src
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "src/composer.json" }}
      # - run:
      #     name: Wait for db
      #     command: dockerize -wait tcp://localhost:3306 -timeout 1m
      # - run: cd src && php artisan migrate
      # - run: cd src && php artisan passport:install
      # run tests!
      # - run: cd src && vendor/bin/phpunit

      - run: cd src && npm install
      - run: ./app_build.sh
